---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: awx-operator
    repo: https://ansible.github.io/awx-operator/
    # valuesInline:
    #   injector:
    #     enabled: false
    releaseName: awx-operator
    version: 2.5.3
